---
- name: install awesomewm package binary and its dependencies
  pacman: name={{ item }} state=installed
  with_items:
    - luajit
    - mesa-libgl
    - xf86-video-vesa
    - xorg-server
    - xorg-xinit
    - xorg-twm

- name: ensure 'awesome' package is not present
  pacman: name={{ item }} state=removed
  with_items:
    - awesome

- name: install luajit-lgi (aur dependency of awesomewm)
  include: aur/pkg.yml pkg_name=luajit-lgi

- name: build and install awesomewm with luajit
  include: aur/pkg.yml pkg_name=awesome-luajit-git

- name: install awesome addons and extensions
  pacman: name={{ item }} state=installed
  with_items:
    - rlwrap
    - vicious
